## What is PANDAS....?
    1. Pandas is Python library.
    2. read, clean, analysis and manipulate.

## Pandas
    - Data manipulate
    - Data Analyze
    - Data Cleaning
    - Data wrangling

### import pandas as pd
### import pandas
### from pandas import series, DataFrame
### from pandas import *

##### !pip install pandas

## Create DataFrame

In [1]:
# series -> 1D  (Dimention)
import pandas as pd
# 1D -> method series
l = [10,20,30]
df = pd.Series(data=l)
print(df)

df = pd.Series([10,20,30,40])
print(df)

0    10
1    20
2    30
dtype: int64
0    10
1    20
2    30
3    40
dtype: int64

In [2]:
import numpy as np
import pandas as pd

data = np.arange(1,5)
df = pd.Series(data)
print(df)

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
import pandas as pd
d = {"Name":"Priyansh","age":20,"roll-no.":123}
df = pd.Series(data=d,index=["Name","age","Roll-no."])
print(df)
print(df["Name"])

Name        Priyansh
age               20
Roll-no.         NaN
dtype: object
Priyansh

In [4]:
# suggestions
# pd.Series() # shift + tab
# help(pd.Series)
# pd.Series??
# print(dir(pd))

# ***DataFrame***

        - Collection of 1d array
        - 2d array
        - Matrix

In [5]:
# 2D -> DataFrame
import pandas as pd
data = {
    "Name" : ["priyansh","nitin","shailja","bulbul"],
    "Roll-no." : [123,456,789,321]
}
df = pd.DataFrame(data=data)
print(df)

# Note :- All arrays must be of the same length
data = {
    "Name" : ["priyansh","nitin","shailja","bulbul"],
    "Roll-no." : [123,456,789,np.nan]
}
df = pd.DataFrame(data=data)
print(df)

       Name  Roll-no.
0  priyansh       123
1     nitin       456
2   shailja       789
3    bulbul       321
       Name  Roll-no.
0  priyansh     123.0
1     nitin     456.0
2   shailja     789.0
3    bulbul       NaN

In [6]:
print(len(data))
print(data.keys())
print(data["Name"][1])
print(data["Roll-no."][2])

2
dict_keys(['Name', 'Roll-no.'])
nitin
789

In [7]:
# by the help of df -> nitin | 789
print(df["Name"][1])
print(df["Roll-no."][2])

nitin
789.0

In [8]:
# Series -> 1D
import pandas as pd
import pandas
from pandas import Series
from pandas import *

l = [10,11,12,13]
df = Series(l)    # from pandas import Series
print(df)

0    10
1    11
2    12
3    13
dtype: int64

In [9]:
# Series -> 1D
import pandas
l = [10,11,12,13]
df = pandas.Series(l)    # import pandas
print(df)

# Question
from pandas import *
import pandas as nitin
n = [10,20,30,40]
df = nitin.Series(n)   # import pandas as nitin
print(df)

0    10
1    11
2    12
3    13
dtype: int64
0    10
1    20
2    30
3    40
dtype: int64

In [10]:
from pandas import *
n = [10,20,30,40]
df = DataFrame(n)
print(df)

    0
0  10
1  20
2  30
3  40

In [11]:
import pandas as pd
d = {"name":"nitin","age":22,"roll-no":123}
df = pd.Series(data=d,index=["name","age","roll-no"])
print(df)

name       nitin
age           22
roll-no      123
dtype: object

In [12]:
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d,index=['a','b','c'])
print(ser)

a    1
b    2
c    3
dtype: int64

In [13]:
# 2D -> DataFrame
import pandas as pd
data = {
    "name" : ["priyansh","nitin","shailja","shilpi"],
    "roll-no" : [123,456,321,654]
}
df = pd.DataFrame(data)
print(df)

       name  roll-no
0  priyansh      123
1     nitin      456
2   shailja      321
3    shilpi      654

## 01/10/2026

## PANDAS
    - reading data
    - cleaning data
    - analyzing data
    - manipulate data

In [14]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\ks\anaconda3\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ks\anaconda3\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ks\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ks\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ks\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [15]:
import pandas as pd    # -> Common to use
# import pandas as nitin
# from pandas import DataFrame
# from pandas import *

In [16]:
# 1D -> Dimension 
import pandas as pd
l = [10,11,12]
df = pd.Series(l)    # df means DataFrame
print(df)

# import numpy as np
# l = [10,11,12]
# arr = np.array(l)
# print(arr)

0    10
1    11
2    12
dtype: int64

In [17]:
# 2D -> Dimension
import pandas as pd
d = {
    "name" : ["one","tow","three","four"],
    "roll-no" : [12,13,14,15]
}
df = DataFrame(d)
print(df)

    name  roll-no
0    one       12
1    tow       13
2  three       14
3   four       15

In [18]:
# 2D 
import pandas as pd
d = {
    "Name" : ["Nitin","Saurabh","Neeraj","Yuvi","Krishna","Payal"],
    "Age" : [21,24,21,21,24,21],
    "Roll-no" : [101,102,103,104,105,106],
    "Gender" : ["Male","Male","Male","Male","Male","Female"],
    "Marks" : [99,98,97,96,95,94]
}
df = pd.DataFrame(d)
print(df)

      Name  Age  Roll-no  Gender  Marks
0    Nitin   21      101    Male     99
1  Saurabh   24      102    Male     98
2   Neeraj   21      103    Male     97
3     Yuvi   21      104    Male     96
4  Krishna   24      105    Male     95
5    Payal   21      106  Female     94

## Save and load data from csv, json, excel

In [19]:
import pandas as pd
# data = pd.read_csv("URL")
# data = pd.read_excel("URL")
# data = pd.read_json("URL")
df = pd.read_csv("student_trainer_list.csv")
print(df)

       Student Name         Trainer
0     Lavesh Gurjar        Deep Sir
1       Divesh Soni        Deep Sir
2      Aryan Sharma        Deep Sir
3      Varun Gahlot        Deep Sir
4     Harsh Pradhan        Deep Sir
5   Priyanka Sharma        Deep Sir
6        Punit Soni        Deep Sir
7     Apoorva Navin        Deep Sir
8     Chhaya Jangid        Deep Sir
9   Aakansha Saxena        Deep Sir
10       Sahil Jain        Deep Sir
11      Sachin Sahu        Deep Sir
12  Rajveer Bumraha        Deep Sir
13    Rahul Kumawat  Ganeshu Sharma
14    Ankit Kumawat  Ganeshu Sharma
15     Abhay Jangir  Ganeshu Sharma
16  Jitendra Jangir  Ganeshu Sharma
17    Rahul Kumawat  Ganeshu Sharma
18       Tej Pratap  Ganeshu Sharma
19    Mukul Kumawat  Ganeshu Sharma
20      Chesta Garg  Ganeshu Sharma
21        Atul Garg  Ganeshu Sharma

In [20]:
d = pd.read_csv("file1.csv")
print(d)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

In [21]:
df.tail(5)

     Student Name         Trainer
17  Rahul Kumawat  Ganeshu Sharma
18     Tej Pratap  Ganeshu Sharma
19  Mukul Kumawat  Ganeshu Sharma
20    Chesta Garg  Ganeshu Sharma
21      Atul Garg  Ganeshu Sharma

In [22]:
d.info

<bound method DataFrame.info of        name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567>

In [23]:
url = pd.read_csv("https://raw.githubusercontent.com/rajendra0968jangid/machine_learning_demo/main/placement.csv")
print(url)

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [24]:
url1 = pd.read_csv("https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file1.csv")
print(url1)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [25]:
data = pd.read_csv("netflix.csv")
print(data)

                                           Title  \
0                               Lets Fight Ghost
1                            HOW TO BUILD A GIRL
2                                     Centigrade
3                                          ANNE+
4                                          Moxie
...                                          ...
15475                     K-POP Extreme Survival
15476            DreamWorks Shreks Swamp Stories
15477  DreamWorks Happy Holidays from Madagascar
15478                DreamWorks Holiday Classics
15479   DreamWorks Kung Fu Panda Awesome Secrets

                                        Genre  \
0      Crime, Drama, Fantasy, Horror, Romance
1                                      Comedy
2                             Drama, Thriller
3                                       Drama
4                     Animation, Short, Drama
...                                       ...
15475                                     NaN
15476                                     NaN
15477               Animation, Comedy, Family
15478               Animation, Comedy, Family
15479       Animation, Action, Comedy, Family

                                                    Tags         Languages  \
0      Comedy Programmes,Romantic TV Comedies,Horror ...  Swedish, Spanish
1           Dramas,Comedies,Films Based on Books,British           English
2                                              Thrillers           English
3            TV Dramas,Romantic TV Dramas,Dutch TV Shows           Turkish
4      Social Issue Dramas,Teen Movies,Dramas,Comedie...           English
...                                                  ...               ...
15475  TV Dramas,TV Programmes,TV Comedies,Romantic T...               NaN
15476  Animal Tales,Family Comedies,Family Adventures...               NaN
15477  TV Comedies,Kids TV,Animal Tales,TV Cartoons,T...           English
15478  TV Comedies,Kids TV,TV Cartoons,TV Programmes,...           English
15479  TV Comedies,Kids TV,Animal Tales,TV Cartoons,T...           English

      Series or Movie  Hidden Gem Score  \
0              Series               4.3
1               Movie               7.0
2               Movie               6.4
3              Series               7.7
4               Movie               8.1
...               ...               ...
15475          Series               NaN
15476          Series               NaN
15477          Series               8.4
15478          Series               8.2
15479          Series               8.1

                                    Country Availability       Runtime  \
0                                               Thailand  < 30 minutes
1                                                 Canada      1-2 hour
2                                                 Canada      1-2 hour
3                                    Belgium,Netherlands  < 30 minutes
4      Lithuania,Poland,France,Iceland,Italy,Spain,Gr...      1-2 hour
...                                                  ...           ...
15475  South Korea,Argentina,United Kingdom,Australia...  < 30 minutes
15476  Russia,Hong Kong,Hungary,Australia,South Korea...  < 30 minutes
15477  Belgium,Switzerland,United States,Germany,Unit...  < 30 minutes
15478  Belgium,Switzerland,Germany,Argentina,United K...  < 30 minutes
15479  Belgium,Switzerland,Germany,United Kingdom,Fra...  < 30 minutes

              Director                      Writer  ... Netflix Release Date  \
0      Tomas Alfredson       John Ajvide Lindqvist  ...           2021-03-04
1        Coky Giedroyc               Caitlin Moran  ...           2021-03-04
2        Brendan Walsh  Brendan Walsh, Daley Nixon  ...           2021-03-04
3                  NaN                         NaN  ...           2021-03-04
4        Stephen Irwin                         NaN  ...           2021-03-04
...                ...                         ...  ...                  ...
15475              NaN                         NaN  ...           2015-04-14
15476              NaN                         NaN  ...           2015-04-14
15477              NaN                         NaN  ...           2015-04-14
15478              NaN                         NaN  ...           2015-04-14
15479              NaN                         NaN  ...           2015-04-14

                             Production House  \
0                   Canal+, Sandrew Metronome
1      Film 4, Monumental Pictures, Lionsgate
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
15475                                     NaN
15476                                     NaN
15477                                     NaN
15478                                     Fox
15479                                     NaN

                                 Netflix Link  \
0      https://www.netflix.com/watch/81415947
1      https://www.netflix.com/watch/81041267
2      https://www.netflix.com/watch/81305978
3      https://www.netflix.com/watch/81336456
4      https://www.netflix.com/watch/81078393
...                                       ...
15475  https://www.netflix.com/watch/80031595
15476  https://www.netflix.com/watch/70242630
15477  https://www.netflix.com/watch/70259784
15478  https://www.netflix.com/watch/70221348
15479  https://www.netflix.com/watch/70241791

                                  IMDb Link  \
0      https://www.imdb.com/title/tt1139797
1      https://www.imdb.com/title/tt4193072
2      https://www.imdb.com/title/tt8945942
3      https://www.imdb.com/title/tt6132758
4      https://www.imdb.com/title/tt2023611
...                                     ...
15475                                   NaN
15476                                   NaN
15477                                   NaN
15478                                   NaN
15479                                   NaN

                                                 Summary  IMDb Votes  \
0      A med student with a supernatural gift tries t...    205926.0
1      When nerdy Johanna moves to London, things get...      2838.0
2      Trapped in a frozen car during a blizzard, a p...      1720.0
3      Upon moving into a new place, a 20-something r...      1147.0
4      Inspired by her moms rebellious past and a con...        63.0
...                                                  ...         ...
15475  Seung Yeon decides to chase her dream of becom...         NaN
15476  Shrek celebrates Halloween, Puss in Boots is c...         NaN
15477  Madagascar goes wild with holiday spirit in th...        71.0
15478  Join your DreamWorks friends for these four ho...        82.0
15479  In this pair of adventures, Po tells the story...        17.0

                                                   Image  \
0      https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...
1      https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...
2      https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...
3      https://occ-0-1489-1490.1.nflxso.net/dnm/api/v...
4      https://occ-0-4039-1500.1.nflxso.net/dnm/api/v...
...                                                  ...
15475  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...
15476  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...
15477  https://occ-0-2773-2774.1.nflxso.net/dnm/api/v...
15478  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...
15479  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...

                                                  Poster  \
0      https://m.media-amazon.com/images/M/MV5BOWM4NT...
1      https://m.media-amazon.com/images/M/MV5BZGUyN2...
2      https://m.media-amazon.com/images/M/MV5BODM2MD...
3      https://m.media-amazon.com/images/M/MV5BNWRkMz...
4      https://m.media-amazon.com/images/M/MV5BODYyNW...
...                                                  ...
15475                                                NaN
15476                                                NaN
15477                                                NaN
15478                                                NaN
15479                                                NaN

                                      TMDb Trailer Trailer Site
0                                              NaN          NaN
1      https://www.youtube.com/watch?v=eIbcxPy4okQ      YouTube
2      https://www.youtube.com/watch?v=0RvV7TNUlkQ      YouTube
3                                              NaN          NaN
4                                              NaN          NaN
...                                            ...          ...
15475                                          NaN          NaN
15476                                          NaN          NaN
15477                                          NaN          NaN
15478                                          NaN          NaN
15479                                          NaN          NaN

[15480 rows x 29 columns]

In [26]:
data.keys()

Index(['Title', 'Genre', 'Tags', 'Languages', 'Series or Movie',
       'Hidden Gem Score', 'Country Availability', 'Runtime', 'Director',
       'Writer', 'Actors', 'View Rating', 'IMDb Score',
       'Rotten Tomatoes Score', 'Metacritic Score', 'Awards Received',
       'Awards Nominated For', 'Boxoffice', 'Release Date',
       'Netflix Release Date', 'Production House', 'Netflix Link', 'IMDb Link',
       'Summary', 'IMDb Votes', 'Image', 'Poster', 'TMDb Trailer',
       'Trailer Site'],
      dtype='str')

In [27]:
# import pandas as pd
# data = pd.read_excel("https://docs.google.com/spreadsheets/d/1r1ppkbQrgNIsY4uuRExo41HTEFtbJ9Qn9MrFVSSVE50/export?format=xlsx")
# print(data)

In [28]:
# head()
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file1.csv"
df = pd.read_csv(url + "?v=2")
print(df)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [29]:
# head() -> starting 5 rows
df.head()

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

In [30]:
# head -> negative
df.head(-5)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356

In [31]:
# tail -> last 5 rows | entry
df.tail()

       name  roll no
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [32]:
# shape
df.shape

(9, 2)

### 05/10/2026

In [33]:
# rename
# print(df)
# print(len(df))
df.rename(columns={"name":"full_name","roll no.":"stu_id"},inplace=True)
print(df)

  full_name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [34]:
# information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_name  9 non-null      str
 1   roll no    9 non-null      int64
dtypes: int64(1), str(1)
memory usage: 335.0 bytes

In [35]:
# describe
df.describe().round()

         roll no
count        9.0
mean    141304.0
std     410000.0
min        123.0
25%       1234.0
50%       3333.0
75%      12345.0
max    1234567.0

In [36]:
import pandas as pd
data = {
    "Emp_ID":  [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary":[50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [37]:
# head
df.head()

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1

In [38]:
# tail
df.tail()

   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [39]:
# information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      6 non-null      int64
 1   Name        6 non-null      str
 2   Department  6 non-null      str
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), str(2)
memory usage: 415.0 bytes

In [40]:
# shape
df.shape

(6, 5)

In [41]:
df

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [42]:
# rename
df.rename(columns={"Emp_ID":"Employee_id","Name":"Employee_name"},inplace=True)
print(df)

   Employee_id Employee_name Department  Salary  Experience
0          101          Amit         IT   50000           2
1          102          Riya         HR   45000           3
2          103           Raj    Finance   60000           5
3          104          Sara         IT   55000           4
4          105          John      Sales   48000           1
5          106          Neha         HR   52000           3

In [43]:
# describe
df.describe().round()

       Employee_id   Salary  Experience
count          6.0      6.0         6.0
mean         104.0  51667.0         3.0
std            2.0   5317.0         1.0
min          101.0  45000.0         1.0
25%          102.0  48500.0         2.0
50%          104.0  51000.0         3.0
75%          105.0  54250.0         4.0
max          106.0  60000.0         5.0

# Operation's on Column's

In [44]:
# Select column
print(df["Employee_id"])  # Employee_id

0    101
1    102
2    103
3    104
4    105
5    106
Name: Employee_id, dtype: int64

In [45]:
print(df[["Employee_name", "Salary"]]) # multiple columns

  Employee_name  Salary
0          Amit   50000
1          Riya   45000
2           Raj   60000
3          Sara   55000
4          John   48000
5          Neha   52000

In [46]:
# add new column
df["Increment"] = [500,1000,1500,2000,1200,1400]
print(df)

   Employee_id Employee_name Department  Salary  Experience  Increment
0          101          Amit         IT   50000           2        500
1          102          Riya         HR   45000           3       1000
2          103           Raj    Finance   60000           5       1500
3          104          Sara         IT   55000           4       2000
4          105          John      Sales   48000           1       1200
5          106          Neha         HR   52000           3       1400

In [47]:
len(df)

6

In [48]:
# deleted column
df.drop("Increment",axis=1,inplace=True)
print(df)

   Employee_id Employee_name Department  Salary  Experience
0          101          Amit         IT   50000           2
1          102          Riya         HR   45000           3
2          103           Raj    Finance   60000           5
3          104          Sara         IT   55000           4
4          105          John      Sales   48000           1
5          106          Neha         HR   52000           3

## 06/10/2026

In [49]:
import pandas as pd
data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Arjun", "Priya", "Karan", "Meena", "David", "Anjali"],
    "Department": ["Marketing", "IT", "HR", "Finance", "Sales", "IT"],
    "Salary": [58000, 62000, 47000, 65000, 51000, 59000],
    "Experience": [3, 5, 2, 6, 2, 4]
}
df = pd.DataFrame(data)
print(df)

   Emp_ID    Name Department  Salary  Experience
0     201   Arjun  Marketing   58000           3
1     202   Priya         IT   62000           5
2     203   Karan         HR   47000           2
3     204   Meena    Finance   65000           6
4     205   David      Sales   51000           2
5     206  Anjali         IT   59000           4

In [50]:
# select column
print(df["Emp_ID"])

0    201
1    202
2    203
3    204
4    205
5    206
Name: Emp_ID, dtype: int64

In [51]:
# add new column 
df["Leaves"] = [10,15,12,9,11,16]
print(df)

   Emp_ID    Name Department  Salary  Experience  Leaves
0     201   Arjun  Marketing   58000           3      10
1     202   Priya         IT   62000           5      15
2     203   Karan         HR   47000           2      12
3     204   Meena    Finance   65000           6       9
4     205   David      Sales   51000           2      11
5     206  Anjali         IT   59000           4      16

In [52]:
# delete column
df.drop("Leaves",axis=1,inplace=True)
print(df)

   Emp_ID    Name Department  Salary  Experience
0     201   Arjun  Marketing   58000           3
1     202   Priya         IT   62000           5
2     203   Karan         HR   47000           2
3     204   Meena    Finance   65000           6
4     205   David      Sales   51000           2
5     206  Anjali         IT   59000           4

In [53]:
# type
print(type(df[["Salary","Experience"]]))

<class 'pandas.DataFrame'>

In [54]:
print(type(df))

<class 'pandas.DataFrame'>

In [55]:
# multi cols delete
df.drop(["Name","Department"],axis=1,inplace=True)
print(df)

   Emp_ID  Salary  Experience
0     201   58000           3
1     202   62000           5
2     203   47000           2
3     204   65000           6
4     205   51000           2
5     206   59000           4

In [56]:
# select multi cols
df[["Emp_ID","Salary"]]

   Emp_ID  Salary
0     201   58000
1     202   62000
2     203   47000
3     204   65000
4     205   51000
5     206   59000

In [57]:
# add new cols
df["Bonus"] = df["Salary"] + 500
print(df)

   Emp_ID  Salary  Experience  Bonus
0     201   58000           3  58500
1     202   62000           5  62500
2     203   47000           2  47500
3     204   65000           6  65500
4     205   51000           2  51500
5     206   59000           4  59500

In [58]:
# add new cols -> increment
df["Increment"] = df["Salary"] * 0.10
print(df)

   Emp_ID  Salary  Experience  Bonus  Increment
0     201   58000           3  58500     5800.0
1     202   62000           5  62500     6200.0
2     203   47000           2  47500     4700.0
3     204   65000           6  65500     6500.0
4     205   51000           2  51500     5100.0
5     206   59000           4  59500     5900.0

In [59]:
# task 
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [60]:
# head
print(df.head())

      name  gender  physics  maths  english
0     arun    Male       88     87       78
1   rajesh    Male       96    100       95
2  moorthy    Male       89     90       70
3     raja    Male       30     25       40
4     usha  Female       67     45       78

In [61]:
# tail
print(df.tail())

       name  gender  physics  maths  english
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [62]:
# shape
print(df.shape)

(14, 5)

In [63]:
print(df.columns)

Index(['name', 'gender', 'physics', 'maths', 'english'], dtype='str')

In [64]:
# type
print(df.dtypes)

name         str
gender       str
physics    int64
maths      int64
english    int64
dtype: object

In [65]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     14 non-null     str
 1   gender   14 non-null     str
 2   physics  14 non-null     int64
 3   maths    14 non-null     int64
 4   english  14 non-null     int64
dtypes: int64(3), str(2)
memory usage: 835.0 bytes
None

In [66]:
print(df.describe())

          physics       maths     english
count   14.000000   14.000000   14.000000
mean    65.857143   71.285714   69.857143
std     26.046872   24.237379   21.205432
min     12.000000   25.000000   23.000000
25%     56.000000   48.250000   67.000000
50%     69.000000   79.000000   74.000000
75%     85.500000   89.750000   78.000000
max    100.000000  100.000000  100.000000

In [67]:
print(df["name"])

0        arun
1      rajesh
2     moorthy
3        raja
4        usha
5       priya
6      Sundar
7     Kavitha
8      Dinesh
9        Hema
10      Gowri
11        Ram
12    Murugan
13    Jenifer
Name: name, dtype: str

In [68]:
print(df[["gender","maths","english"]])

    gender  maths  english
0     Male     87       78
1     Male    100       95
2     Male     90       70
3     Male     25       40
4   Female     45       78
5   Female     46       78
6     Male     67       67
7   Female     71       67
8     Male     45       67
9   Female     90       23
10  Female    100      100
11    Male     55       47
12    Male     89       78
13  Female     88       90

In [69]:
print(df.loc[2])

name       moorthy
gender        Male
physics         89
maths           90
english         70
Name: 2, dtype: object

In [70]:
male = df[df["gender"] == "Male"]
print(male)

       name gender  physics  maths  english
0      arun   Male       88     87       78
1    rajesh   Male       96    100       95
2   moorthy   Male       89     90       70
3      raja   Male       30     25       40
6    Sundar   Male       12     67       67
8    Dinesh   Male       56     45       67
11      Ram   Male       78     55       47
12  Murugan   Male       34     89       78

In [71]:
df["Total"] = df["physics"] + df["maths"] + df["english"]
print(df)

       name  gender  physics  maths  english  Total
0      arun    Male       88     87       78    253
1    rajesh    Male       96    100       95    291
2   moorthy    Male       89     90       70    249
3      raja    Male       30     25       40     95
4      usha  Female       67     45       78    190
5     priya  Female       56     46       78    180
6    Sundar    Male       12     67       67    146
7   Kavitha  Female       78     71       67    216
8    Dinesh    Male       56     45       67    168
9      Hema  Female       71     90       23    184
10    Gowri  Female      100    100      100    300
11      Ram    Male       78     55       47    180
12  Murugan    Male       34     89       78    201
13  Jenifer  Female       67     88       90    245

In [72]:
df["Percentage"] = (df["Total"] / 300) * 100
print(df)

       name  gender  physics  maths  english  Total  Percentage
0      arun    Male       88     87       78    253   84.333333
1    rajesh    Male       96    100       95    291   97.000000
2   moorthy    Male       89     90       70    249   83.000000
3      raja    Male       30     25       40     95   31.666667
4      usha  Female       67     45       78    190   63.333333
5     priya  Female       56     46       78    180   60.000000
6    Sundar    Male       12     67       67    146   48.666667
7   Kavitha  Female       78     71       67    216   72.000000
8    Dinesh    Male       56     45       67    168   56.000000
9      Hema  Female       71     90       23    184   61.333333
10    Gowri  Female      100    100      100    300  100.000000
11      Ram    Male       78     55       47    180   60.000000
12  Murugan    Male       34     89       78    201   67.000000
13  Jenifer  Female       67     88       90    245   81.666667

In [73]:
df["Result"] = "Failed"
df.loc[df["Percentage"] >= 60, "Result"] = "Pass"
print(df)

       name  gender  physics  maths  english  Total  Percentage  Result
0      arun    Male       88     87       78    253   84.333333    Pass
1    rajesh    Male       96    100       95    291   97.000000    Pass
2   moorthy    Male       89     90       70    249   83.000000    Pass
3      raja    Male       30     25       40     95   31.666667  Failed
4      usha  Female       67     45       78    190   63.333333    Pass
5     priya  Female       56     46       78    180   60.000000    Pass
6    Sundar    Male       12     67       67    146   48.666667  Failed
7   Kavitha  Female       78     71       67    216   72.000000    Pass
8    Dinesh    Male       56     45       67    168   56.000000  Failed
9      Hema  Female       71     90       23    184   61.333333    Pass
10    Gowri  Female      100    100      100    300  100.000000    Pass
11      Ram    Male       78     55       47    180   60.000000    Pass
12  Murugan    Male       34     89       78    201   67.000000    Pass
13  Jenifer  Female       67     88       90    245   81.666667    Pass

In [74]:
import pandas as pd
data = {
    "name":["aman","rahul","priya"],
    "age":[20,21,22]
}
df = pd.DataFrame(data,index=["a","b","c"])
print(df)

    name  age
a   aman   20
b  rahul   21
c  priya   22

In [75]:
# loc
print(df.loc["c"])

name    priya
age        22
Name: c, dtype: object

In [76]:
# loc
print(df.loc["b","age"])

21

In [77]:
# iloc
print(df.iloc[1])

name    rahul
age        21
Name: b, dtype: object

In [78]:
# iloc
print(df.iloc[1,1])

21

In [79]:
# add -> rows and cols
# update -> rows and cols
# delete -> rows and cols

## Filter Operation

In [80]:
import pandas as pd
data = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(data)
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [81]:
filter_data = df["maths"] > 50
# print(filter_data)
print(df[df["maths"] > 50])

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [84]:
# english
print(df[df["english"] < 60])

    name  gender  physics  maths  english
3   raja    Male       30     25       40
9   Hema  Female       71     90       23
11   Ram    Male       78     55       47

In [87]:
# physics marks equal to 78
print(df[df["physics"] == 78])

       name  gender  physics  maths  english
7   Kavitha  Female       78     71       67
11      Ram    Male       78     55       47

In [88]:
# physics marks not-equal to 78
print(df[df["physics"] != 78])

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [90]:
# name equal to sundar
print(df[df["name"] == "Sundar"])

     name gender  physics  maths  english
6  Sundar   Male       12     67       67

In [91]:
# print users where maths marks > 60 and english marks < 60
print(df[(df["maths"] > 60) & (df["english"] < 60)])

   name  gender  physics  maths  english
9  Hema  Female       71     90       23

In [93]:
# print users where gender is male and maths marks > 60
print((df[(df["gender"] == "Male") & (df["maths"] > 60)]))

       name gender  physics  maths  english
0      arun   Male       88     87       78
1    rajesh   Male       96    100       95
2   moorthy   Male       89     90       70
6    Sundar   Male       12     67       67
12  Murugan   Male       34     89       78

In [94]:
# print users where gender is male or maths marks > 60
print((df[(df["gender"] == "Male") | (df["maths"] > 60)]))

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [98]:
# print physics > 60 and english < 60
print(df[(df["physics"] > 60) & (df["english"] < 60)]["physics"])

9     71
11    78
Name: physics, dtype: int64

In [99]:
print(df[(df["physics"] > 60) & (df["english"] < 60)][["physics","maths"]])

    physics  maths
9        71     90
11       78     55

In [101]:
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [108]:
print(df.sort_values(["name","gender","physics","maths","english"])) # ascending

       name  gender  physics  maths  english
8    Dinesh    Male       56     45       67
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
13  Jenifer  Female       67     88       90
7   Kavitha  Female       78     71       67
12  Murugan    Male       34     89       78
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
0      arun    Male       88     87       78
2   moorthy    Male       89     90       70
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
4      usha  Female       67     45       78

In [104]:
print(df.sort_values("maths" , ascending=False)) # discending

       name  gender  physics  maths  english
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
2   moorthy    Male       89     90       70
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
0      arun    Male       88     87       78
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
5     priya  Female       56     46       78
4      usha  Female       67     45       78
8    Dinesh    Male       56     45       67
3      raja    Male       30     25       40